---
kind: Service
apiVersion: v1
metadata:
  name: todo
  labels:
    name: todo
  namespace: $WERCKER_GIT_BRANCH
spec:
  ports:
    - port: 80
      targetPort: http-server
      protocol: TCP
  selector:
    name: todo
