---
kind: Service
apiVersion: v1
metadata:
  name: todo
  labels:
    name: todo
spec:
  ports:
    - port: 80
      targetPort: http-server
      protocol: TCP
  externalIPs:
    - 188.166.42.144
  selector:
    name: todo
